name: Commander-WorldGuard-EVM
version: 1.0
description: Provides an EVM to the WorldGuard plugin
author: Tustin2121
main: org.digiplex.bukkitplugin.commander.ev.CmdrWorldGuardEVPlugin
depend: [Commander, WorldGuard]
